version: '3'
services:
  backend1:
    build: ./backend
    container_name: backend1
    ports:
      - "5001:5000"
    restart: always

  backend2:
    build: ./backend
    container_name: backend2
    ports:
      - "5002:5000"
    restart: always

  postgres:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: game_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend1
      - backend2

volumes:
  postgres_data:
