version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/guess_game
    restart: unless-stopped
    expose:
      - "5000"
    depends_on:
      - db  # Garante que o backend depende do db estar disponível

  db:
    image: postgres:13
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: guess_game
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - backend
      - db  # Certifica-se que o backend e o banco de dados estão prontos antes de iniciar o frontend
    expose:
      - "80"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html
    ports:
      - "8082:80"
    depends_on:
      - backend
      - db
    restart: unless-stopped

volumes:
  db_data:
